# Generated by Django 5.0.6 on 2024-07-22 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_emailverification_pendinguser'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendinguser',
            name='first_name',
            field=models.CharField(default=datetime.datetime(2024, 7, 22, 16, 35, 47, 273571, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='last_name',
            field=models.CharField(default=datetime.datetime(2024, 7, 22, 16, 36, 12, 293765, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendinguser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
