# Generated by Django 5.0.6 on 2024-07-22 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pendinguser_first_name_pendinguser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='email',
            field=models.EmailField(default=datetime.datetime(2024, 7, 22, 18, 5, 2, 260407, tzinfo=datetime.timezone.utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailverification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
